# version: "2.16"
services:

  back:
    build: "./back_readmore"
    container_name: Django-back
    volumes:
      - ./back_readmore:/usr/back
    ports:
      - 8080:8000

  front:
    build: "./front-readmore"
    container_name: Node-front
    volumes:
      - ./front-readmore:/usr/front
    ports:
      - 19000:19000
    depends_on:
      - back